AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal MSK Serverless cluster with IAM auth and optional CloudWatch logging

Parameters:
  MskSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Private subnet IDs for the MSK serverless cluster
  MskSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group for the MSK cluster
  EnableCloudWatchLogs:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']
    Description: Enable CloudWatch Logs for the MSK cluster

Conditions:
  EnableLogs: !Equals [!Ref EnableCloudWatchLogs, 'true']

Resources:
  MskLogGroup:
    Type: AWS::Logs::LogGroup
    Condition: EnableLogs
    Properties:
      LogGroupName: !Sub '/aws/msk/${AWS::StackName}'
      RetentionInDays: 7

  MskCluster:
    Type: AWS::MSK::ServerlessCluster
    Properties:
      ClusterName: !Sub '${AWS::StackName}'
      ClientAuthentication:
        Sasl:
          Iam:
            Enabled: true
      VpcConfigs:
        - SubnetIds: !Ref MskSubnetIds
          SecurityGroups:
            - !Ref MskSecurityGroupId
      LoggingInfo:
        BrokerLogs:
          CloudWatchLogs: !If [EnableLogs, {Enabled: true, LogGroup: !Ref MskLogGroup}, {Enabled: false}]

Outputs:
  MskClusterArn:
    Value: !Ref MskCluster
    Description: ARN of the MSK Serverless cluster
