AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal MSK Serverless cluster with IAM authentication

Parameters:
  MskSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Private subnet IDs for the MSK serverless cluster
  MskSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group for the MSK cluster
Resources:
  MskCluster:
    Type: AWS::MSK::ServerlessCluster
    Properties:
      ClusterName: !Sub '${AWS::StackName}'
      ClientAuthentication:
        Sasl:
          Iam:
            Enabled: true
      VpcConfigs:
        - SubnetIds: !Ref MskSubnetIds
          SecurityGroups:
            - !Ref MskSecurityGroupId

Outputs:
  MskClusterArn:
    Value: !Ref MskCluster
    Description: ARN of the MSK Serverless cluster
